### ISSUE TITLE
`IsConsole` just checks whether the writer is stdin, stdout or stderr, which is not reliable

### ISSUE THREAD

**Issue by ChipZhang** [gookit/color#14]
```
func IsConsole(out io.Writer) bool {
	o, ok := out.(*os.File)
	if !ok {
		return false
	}

	return o == os.Stdout || o == os.Stderr || o == os.Stdin
}
```

```
func TestOther(t *testing.T) {
	is := assert.New(t)

	is.True(IsConsole(os.Stdout))
	is.False(IsConsole(&bytes.Buffer{}))
```

Sometimes the standard input / output / error streams are redirected to files. In such cases, `IsConsole` will still return true, but the writer is not a console or terminal

**Comment by inhere** [comment]
hi @ChipZhang 

fixed by:

https://github.com/gookit/color/blob/d6a4feb4049c07716378f6e08cd78692b9c7b848/utils.go#L28-L38
