### ISSUE TITLE
Color on Windows in cygwin, powershell, cmd

### ISSUE THREAD

**Issue by tomcruise81** [gookit/color#16]
This tool looks really promising! So thanks in advance.

I'm running into some issues with your `isSupportColor` method on Windows, which affects `RenderCode`.

1. Pure git-bash:
   - `$MSYSTEM` = `MINGW64`
   - `$TERM` = `xterm`
   - 256 coloration seems to work
2. ConsoleZ git-bash (started via `C:\Program Files\Git\bin\sh.exe --login -i`)
   - `$MSYSTEM` = `MINGW64`
   - `$TERM` = `cygwin`
   - coloration is disabled
   - 16-color coloration is possible via github.com/fatih/color - `Output`
3. CMD:
   - `%CMDEXTVERSION%` = `2`
   - coloration is disabled
   - 16-color coloration is possible via github.com/fatih/color - `Output`
4. Powershell:
   - Version: 5.1.16299.1146
   - coloration is disabled
   - 16-color coloration is possible via github.com/fatih/color - `Output`

My method for testing includes creating a `color.C256` object and using it's `Sprint` method to output the string to write to a github.com/fatih/color - `Output` Writer.

Thanks!

**Comment by tomcruise81** [comment]
For additional context, I utilize github.com/fatih/color - `NoColor` to determine if STDOUT supports color. For every scenario that I've listed above, `NoColor` is `false`. In fact, the only scenario in which I run into it being `true` is when I'm debugging an application in something like VS Code.

**Comment by inhere** [comment]
`IsSupportColor` 也许是不准确的在Windows下面。

在Windows下面会再检查一次得到 `isLikeInCmd`，通过这个来判断如何渲染：

https://github.com/gookit/color/blob/591f6560c5a12dbd36ab13649df8847b76eb2305/utils.go#L185-L206

windows PowerShell，cmd 环境代码参考：

https://github.com/gookit/color/blob/591f6560c5a12dbd36ab13649df8847b76eb2305/color_windows.go#L127-L188

**Comment by tomcruise81** [comment]
@inhere - thanks! Is there any benefit to just utilizing:
- github.com/mattn/go-isatty like https://github.com/fatih/color/blob/master/color.go#L20-L21
- github.com/mattn/go-colorable like https://github.com/fatih/color/blob/master/color.go#L23-L28

Is there any possibility of making the following public so that they could be overridden:
- `isSupportColor` - https://github.com/gookit/color/blob/591f6560c5a12dbd36ab13649df8847b76eb2305/color.go#L54
- `output` - https://github.com/gookit/color/blob/591f6560c5a12dbd36ab13649df8847b76eb2305/color.go#L46

**Comment by tomcruise81** [comment]
Nevermind to that last bit - I found how you'd already done it - https://github.com/gookit/color/blob/591f6560c5a12dbd36ab13649df8847b76eb2305/color.go#L94-L110

**Comment by inhere** [comment]
@tomcruise81 Yes.

Is there anything else that needs improvement?

**Comment by tomcruise81** [comment]
Not right now, I think I can work with this. Thanks!
