### ISSUE TITLE
How to "ignore" html styles

### ISSUE THREAD

**Issue by ghostsquad** [gookit/color#17]
I'd like to print raw HTML colored, and I don't want `gookit/color` to interpret the HTML in the string. Is there a way to ignore the HTML?

**Comment by inhere** [comment]
hi, How do you use it ?

**Comment by ghostsquad** [comment]
```
green := color.FgGreen.Render 	fmt.Printf("%s", red(couldHaveHtml))
```

Or any other way described in the readme. I don't want `gook/color` to interpret the contents of the string in any way.

Partially because the string contents could be arbitrary, but also for performance reasons.

**Comment by inhere** [comment]
hi 

all basic color(eg: `color.Red`) and style and theme (eg: `color.Info`) will don't handle html tag.

color tag only parsed on call  `color.Print` `color.Println` `color.Render`

**Comment by ghostsquad** [comment]
What about with 256 colors?

```
c := color.C256(132) // fg color c.Println("message")
```

**Comment by inhere** [comment]
do not worry! 

Except for `color.XPrint` `color.PrintX` `color.Render/color.String/color.Text`, will not check and handle HTML TAG.

**Comment by ghostsquad** [comment]
Thanks!
