### ISSUE TITLE
256-Color and RGB not working

### ISSUE THREAD

**Issue by arsalahmed786** [gookit/color#20]
Hi, i tried your example it print message only in default gray color.

**Comment by inhere** [comment]
hi, Could you please provide us with your operating environment? and more information, tks

**Comment by arsalahmed786** [comment]
What do you mean? Sorry i'm not programmer but i know basics. I have my tool sources in golang and now how to build how i'm trying to change color but i can only use 

color.Bold
color.Black
color.White
color.Gray
color.Red
color.Green
color.Yellow
color.Blue
color.Magenta
color.Cyan

**Comment by inhere** [comment]
oh,hi

Please paste your code

**Comment by arsalahmed786** [comment]
> oh,hi
> 
> Please paste your code

I just used your example, I'm using windows 10, Git for build it into .go and Visual studio code for edit.

**Comment by inhere** [comment]
hi, your local package version is latest?

**Comment by arsalahmed786** [comment]
which version Golang? or Git? OR your package? and how to check. And as i told you i'm not developer could you tell me how can i change. By the way thanks for great package and helping me.

**Comment by inhere** [comment]
has go.mod file? content should contains like `github.com/gookit/color v1.2.7`. the `v1.2.7` is version of gookit/color

**Comment by arsalahmed786** [comment]
I use Import "github.com/gookit/color"

**Comment by arsalahmed786** [comment]
I copy paste your example and build it but i don't see custom colors in windows cmd. i'm using windows 10

**Comment by inhere** [comment]
Which example file?

**Comment by arsalahmed786** [comment]
I can't use 256 or hex or RGB color code. 

I can only use these colors.
color.Bold
color.Black
color.White
color.Gray
color.Red
color.Green
color.Yellow
color.Blue
color.Magenta
color.Cyan

If i use this
color.HEX("#1976D2").Println("blue-darken")
color.HEX("#D50000", true).Println("red-accent. use HEX style")

It will print text in default gray color.

**Comment by inhere** [comment]
please update to latest version `v1.3.0`
