### ISSUE TITLE
Use terminfo instead of hardcoding a list of terminals

### ISSUE THREAD

**Issue by vincentbernat** [gookit/color#25]
Hey!

You should use terminfo instead of relying on the terminal name in TERM. This can provide you the number of colors supported. Otherwise, you are missing a lot of terminals supporting colors, like `rxvt` or `screen`. In Go, it seems https://github.com/xo/terminfo can do that. It also seems to handle some edge cases for terminals not using the correct TERM. It also handles the special case of true color which was not available through terminfo until recently and is able to fallback to `COLORTERM` (but it should be using Tc if available).

**Comment by Delta456** [comment]
Please use this instead of hardcore logic 🙏

**Comment by Delta456** [comment]
Also WSL has true color support.

**Comment by Delta456** [comment]
Here's how I did it https://github.com/Delta456/box-cli-maker/blob/dev/util.go, see `detectTerminal` function

**Comment by inhere** [comment]
ok, thanks

**Comment by inhere** [comment]
hi @vincentbernat  @Delta456 

Thanks you.

I refer `xo/terminfo.detectColorLevelFromEnv` and `https://github.com/Delta456/box-cli-maker`, rewrite the detect method: `detectTermColorLevel()`

code please see https://github.com/gookit/color/blob/master/detect_env.go

**Comment by Delta456** [comment]
@inhere Amazing! Would appreciate if you could also add my repo in the `REAMDE.md`.

**Comment by Delta456** [comment]
Also I believe you could had imported my module and use it instead of making one.

**Comment by inhere** [comment]
hi @Delta456 

Your module also has some problems, please see my detection code

https://github.com/gookit/color/blob/1459bf6721d7922eb65ecf2eff7de95819a35fa2/detect_env.go#L31-L156

And my package as the base package, can not rely on your application package in reverse. :)
