### ISSUE TITLE
Did not work on ubuntu 19.04

### ISSUE THREAD

**Issue by kyp0717** [gookit/color#3]
Hi. I ran the demo.go to test and it did not work.  
I am on ubuntu linux 19.04. 
Thanks.

**Comment by inhere** [comment]
thank you for your feedback.

**Comment by inhere** [comment]
thank you for your feedback.

**Comment by inhere** [comment]
hi @kyp0717 

Just now, I tested it on Ubuntu 19.04 and it works very well.

![image](https://user-images.githubusercontent.com/5302062/62357121-02736a80-b545-11e9-8fb6-aa3f2e74ad12.png)
