### ISSUE TITLE
feature request: provide func(RGBColor) C16() Color

### ISSUE THREAD

**Issue by Delta456** [gookit/color#31]
As we have a function to round off true color to 256 colors, can we allow have a method to round off true color to 16 colors?

**Comment by inhere** [comment]
now have:

```go
// C256 returns the closest approximate 256 (8 bit) color
func (c RGBColor) C256() Color256
```

util func:

```go
// Rgb2short convert RGB-code to 256-code
func Rgb2short(r, g, b uint8) uint8
```

**Comment by Delta456** [comment]
You can look at how [rich](https://github.com/willmcgugan/rich) does it.

**Comment by Delta456** [comment]
Here

https://github.com/willmcgugan/rich/blob/0d2ed27835fc66c1d3f9a6f5b2eeac0cc688e585/rich/color.py#L468-L488

**Comment by inhere** [comment]
@Delta456  thanks

**Comment by Delta456** [comment]
It is there in that file, my bad that I didn't link the correct one 😅 

Side note: I am using your module for [my module](https://github.com/Delta456/box-cli-maker), see the dev branch

![image](https://user-images.githubusercontent.com/28479139/100716628-f6204b80-33de-11eb-8c37-1b3b9cba787e.png)

**Comment by inhere** [comment]
ok, thanks

**Comment by Delta456** [comment]
Please do tell when you can implement it, really need it.

**Comment by inhere** [comment]
hi @Delta456  you can use `color.Print/color.Println` instead of the `fmt.Print/fmt.Println`

https://github.com/Delta456/box-cli-maker/blob/df718f3ba00272fe470235e24f3e6931ab932238/box.go#L266
https://github.com/Delta456/box-cli-maker/blob/df718f3ba00272fe470235e24f3e6931ab932238/box.go#L298

**Comment by Delta456** [comment]
`fmt.Println` works for me in windows powershell, windows cmd and windows terminal.

**Comment by Delta456** [comment]
Found it https://github.com/radareorg/radare2/blob/master/libr/cons/rgb.c#L249-L271

**Comment by inhere** [comment]
hi @Delta456 added on https://github.com/gookit/color/commit/079365ccbb1555d5fc503588bbf4bcc2e4ae2201

**Comment by Delta456** [comment]
@inhere omg thanks, can you do a new release for it?

**Comment by inhere** [comment]
released https://github.com/gookit/color/releases/tag/v1.3.3

**Comment by Delta456** [comment]
Thank you so much ❤️
