### ISSUE TITLE
windows Using version v1.3.5 Printing does not display colors properly

### ISSUE THREAD

**Issue by 18211167516** [gookit/color#33]
![image](https://user-images.githubusercontent.com/21099213/103114523-de647c00-4699-11eb-9860-2b925824d764.png)

**Comment by inhere** [comment]
windows cmd.exe ?

**Comment by inhere** [comment]
Hi, It can work on my windows machine. 
Please provide the system information and `env` information

**Comment by 18211167516** [comment]
Yes, it is cmd.exe, my windows machine windows8.1

**Comment by inhere** [comment]
please use latest version try again
