### ISSUE TITLE
colors don't work on windows with git for windows while using vscode

### ISSUE THREAD

**Issue by Delta456** [gookit/color#35]
**System (please complete the following information):**

 - OS: Windows 10
 - GO Version: 1.1.5
 - Pkg Version: Latest

**Describe the bug**

**To Reproduce**

Use [my module](https://github.com/Delta456/box-cli-maker) and run `go test -v .`

**Expected behavior**

Same output as Windows Terminal

![image](https://user-images.githubusercontent.com/28479139/106578661-c53acf00-6565-11eb-95e8-82139b32ea9c.png)

**Screenshots**

What I get:

![image](https://user-images.githubusercontent.com/28479139/106578772-e8657e80-6565-11eb-9831-3c494df8ed1a.png)

**Additional context**

The screenshot is from VsCode but the same problem doesn't happen in Git Bash.

**Comment by inhere** [comment]
sorry, I don't have a Windows environment right now.

**Comment by Delta456** [comment]
I can help if you tell me what to do!

**Comment by inhere** [comment]
Please print ENV information on VsCode (Note: Please delete private information)

**Comment by inhere** [comment]
there are some tests on my windows.

- windows cmd on VSCode

![捕获002](https://user-images.githubusercontent.com/5302062/107120598-6fe62100-68c9-11eb-8edd-269e5c6ad7e4.JPG)

- windows powerShell on VSCode

![捕获001](https://user-images.githubusercontent.com/5302062/107120548-301f3980-68c9-11eb-85db-dc3db4f76fbb.JPG)

**Comment by Delta456** [comment]
Can you try git for windows?

**Comment by inhere** [comment]
**windows git-cmd.exe on VSCode**

![捕获003](https://user-images.githubusercontent.com/5302062/107123191-2997be80-68d7-11eb-92cc-31abad23f0c0.JPG)

**windows git/bin/bash.exe on VSCode**

![捕获004](https://user-images.githubusercontent.com/5302062/107123192-2bfa1880-68d7-11eb-8802-9318a05d2e4c.JPG)

**windows git-bash.exe on VSCode**

![捕获005](https://user-images.githubusercontent.com/5302062/107123194-2d2b4580-68d7-11eb-9a6c-9a97d4a44a11.JPG)

**Comment by Delta456** [comment]
What's your git for windows version?

**Comment by Delta456** [comment]
Can you please clone my module and run `go test -v .`?

**Comment by inhere** [comment]
Wait for me to have a try in the evening.

**Comment by inhere** [comment]
> What's your git for windows version?

My git version:

```
$ git version
git version 2.24.0.windows.2
```

**Comment by Delta456** [comment]
Please do

**Comment by inhere** [comment]
- Windows git/bin/bash.exe on VSCode

![git-bin-bash](https://user-images.githubusercontent.com/5302062/107150785-99bb4880-699a-11eb-88a1-4838f148de4f.JPG)

**Comment by Delta456** [comment]
Do you see the if the colored ones are colored? If so can you send a screenshot.

**Comment by inhere** [comment]
![git-bin-bash2](https://user-images.githubusercontent.com/5302062/107151215-5b268d80-699c-11eb-8690-316d9d992ca1.JPG)

**Comment by inhere** [comment]
![git-cmd](https://user-images.githubusercontent.com/5302062/107151267-9b860b80-699c-11eb-9b93-19fd7e28dc3a.JPG)

**Comment by Delta456** [comment]
It's so weird that it doesn't work for me 🥺 What's your VsCode version? I have updated to Git for Windows to 2.30.0 as I think the latest one is causing the issue.

**Comment by inhere** [comment]
```
Version: 1.53.0 (user setup)
Commit: 8490d3dde47c57ba65ec40dd192d014fd2113496
Date: 2021-02-03T20:36:38.611Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by Delta456** [comment]
Can you update your update your Git for Windows to the latest version and try again please? I just really don't understand why is it happening on my end.

**Comment by inhere** [comment]
What's your windows version?

**Comment by Delta456** [comment]
Windows 10

**Comment by Delta456** [comment]
Have you updated to the latest Git for Windows Version and is it working for you?

**Comment by Delta456** [comment]
Have you tried?

**Comment by inhere** [comment]
Wait for me to try at night. I only have a Windows computer at home

**Comment by inhere** [comment]
I have uprade git to latest version.

```bash
$ git version
git version 2.30.0.windows.2
```

- Windows git-cmd.exe on VSCode

![git-cmd2](https://user-images.githubusercontent.com/5302062/107383843-5b559300-6b2c-11eb-9b44-49623514067c.JPG)

**Comment by Delta456** [comment]
I am no longer using Windows can't test this :sweat_smile:

**Comment by inhere** [comment]
ok,thanks

**Comment by inhere** [comment]
@footfish  It works on my windows 10!

![image](https://user-images.githubusercontent.com/5302062/137583646-52abc26b-a0a3-4cb2-9090-e77677bf163c.png)

**Comment by inhere** [comment]
@footfish 

![](https://user-images.githubusercontent.com/12461463/137601906-2f86de06-86a7-4cab-9ebd-51d2c1713cd9.png)

shell env is ? 

terminal config in my vscode:

```json
	"terminal.external.windowsExec": "D:\\Program Files\\Tools\\Git\\bin\\bash.exe",
    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        },
        "CMD": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": [],
            "icon": "terminal-cmd"
        },
        "Git-Bash": {
            // "source": "Git Bash"
            "path": "D:\\Program Files\\Tools\\Git\\bin\\bash.exe"
        },
        "Windows PowerShell": {
            "path": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
        }
    },
    "terminal.integrated.defaultProfile.windows": "Git-Bash"
```

**Comment by footfish** [comment]
The one that does not work is bash (without ANSICON, of course)
![image](https://user-images.githubusercontent.com/12461463/137642131-933e4018-ec3f-4e7e-bdde-7b3110c74c05.png)

![image](https://user-images.githubusercontent.com/12461463/137642225-1fe07497-7735-4667-8d32-775e68b6da73.png)
