### ISSUE TITLE
No color after v1.4.0 upgrade

### ISSUE THREAD

**Issue by babykart** [gookit/color#38]
**System:**

 - OS: `linux`
 - GO Version: `1.16`
 - Pkg Version: `1.4.0`
 
 ```
 TERM=xterm
 ```

**Describe the bug**

After upgrading to 1.4.0, no more color in output, without error.

**To Reproduce**

Upgrade to v1.4.0.

```
green := color.FgGreen.Render
fmt.Println(">>> Blah :", green("blahblah"))
```

**Expected behavior**

The color must be printed as expected.

**Comment by inhere** [comment]
hi @babykart thanks

> terminfo load error, has been fixed. 

Please upgrade to `v1.4.1` and try again.

**Comment by babykart** [comment]
Fixed! Thank you!

**Comment by babykart** [comment]
Well, not really after a second test ....

**Comment by inhere** [comment]
> Well, not really after a second test ....

?? :)

**Comment by babykart** [comment]
With v1.4.1 there isn't color displayed, same as the v1.4.0.
Rollback to 1.3.8 all my code working fine.
I'm sorry but there isn't any error to explain this, just all my outputs aren't colorized after the upgrade.

**Comment by inhere** [comment]
Your linux release version is?

**Comment by babykart** [comment]
A gentoo base system in a container:

```cat /etc/os-release
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"```

**Comment by inhere** [comment]
hi @babykart  can you upgrade to `1.4.2` for try. thanks you! :)

**Comment by babykart** [comment]
Hi @inhere , my colored outputs come back! thanks you for my eyes .... ;)
You can close the issue...

**Comment by inhere** [comment]
ok, thanks you
