### ISSUE TITLE
color.Pintln does not add spaces as fmt.Println does

### ISSUE THREAD

**Issue by Tuurlijk** [gookit/color#4]
fmt.Println will add spaces if called like:
`fmt.Println("hello", "world")` -> "hello world"

If I do:
`color.Println("<comment>hello</>", "world")`

expected result: "hello world"

actual result: "helloworld"

**Comment by inhere** [comment]
@Tuurlijk Thanks for your report, I will fix it as soon as possible.

**Comment by inhere** [comment]
hi @Tuurlijk 

I have fixed it and released a new version. thank you.
