### ISSUE TITLE
Question: How to escape color tags

### ISSUE THREAD

**Issue by SJrX** [gookit/color#45]
I'm using the HTML like tags feature to pretty print some JSON, but I'm concerned that occasionally the JSON data might have tags like <red> that would start getting rendered as a color. I did a search and replace and didn't see anything, so was wondering if there was a way to escape or encode tags to make it so that color tags aren't injected?

**Comment by inhere** [comment]
color pkg use tag like: `<b>some words</>`, it is different from HTML tags.

can you provide an error example?

------
OR, not use tag render color, use like `color.Info.Sprint("some words")`
