### ISSUE TITLE
Color not working on Manjaro

### ISSUE THREAD

**Issue by SidoShiro** [gookit/color#6]
Here the output from the demo, I was expecting your nice colors: unfortunately it's all white.

![image](https://user-images.githubusercontent.com/22345593/68474738-8add6780-0226-11ea-9cd4-c838deab2195.png)

> What do you think the problem is ? Did you encounter such problem ?

* NeoFetch output if needed:
```
OS: Manjaro Linux x86_64 
Kernel: 4.19.81-1-MANJARO
Shell: bash 5.0.11 
Resolution: 1920x1080 
WM: i3 
Theme: Adwaita [GTK3] 
Icons: Adwaita [GTK3] 
Terminal: urxvt 
Terminal Font: DejaVu Sans Mono
```

Thank  you for your time,

**Comment by inhere** [comment]
thank you for report issue.

**Comment by SidoShiro** [comment]
I noticed that in GoLand, JetBrains IDE.
The colors are working correctly....

![colorsGO_goland](https://user-images.githubusercontent.com/22345593/68659097-f11ffe00-0536-11ea-9773-5cbe1fd7e714.png)

**Comment by inhere** [comment]
Sorry  @SidoShiro 

I am looking for a go environment based on the manjaro docker system for testing. But did not find .... :(

**Comment by SidoShiro** [comment]
Hi!

I think the problem might come from my terminal :
rxvt-unicode-256color


I will try to check more when I will have more time.

**Comment by inhere** [comment]
hi @SidoShiro Thank you for your help

**Comment by JensChrG** [comment]
I also see this issue on rxvt-unicode-256color, but on Ubuntu.
It works fine in gnome-terminal.

**Comment by inhere** [comment]
hi @SidoShiro @JensChrG maybe is color check fail. at: 

https://github.com/gookit/color/blob/ecea05b3eccbc26b9c388d10f97e4d413deb3c29/utils.go#L36-L59

**Comment by inhere** [comment]
@SidoShiro can you paste result for exec `env | grep TERM`

**Comment by JensChrG** [comment]
> @SidoShiro can you paste result for exec `env | grep TERM`

COLORTERM=rxvt-xpm
TERM=rxvt-unicode-256color

**Comment by inhere** [comment]
@JensChrG  thanks you.

**Comment by inhere** [comment]
@JensChrG  @SidoShiro  I have fixed it. Please try again.

**Comment by SidoShiro** [comment]
Hi !
Sorry I haven't checked the issue :( 
Good job !!!! Just pulled the repository and it worked. Well done to both of you @JensChrG @inhere 
![2020-01-18-202946_1920x1080_scrot](https://user-images.githubusercontent.com/22345593/72669428-d9cb2880-3a31-11ea-9532-6f940a1ecd7e.png)

**Comment by inhere** [comment]
@SidoShiro Ok, thanks you reply.

**Comment by JensChrG** [comment]
It also works for me now, thanks.
