### ISSUE TITLE
[QUESTION] What is the rgb color code for `color.HiCyan`?

### ISSUE THREAD

**Issue by rew1nter** [gookit/color#65]
I really like this cyan and want to use it somewhere else. But I couldn't find it after searching the source

**Comment by inhere** [comment]
hi @rew1nter This is a examples:

```go
rgb := color.HiCyan.RGB() // convert to rgb color
rgb.Println("message with rgb color")

rgb := color.HiCyan.ToBg().RGB() // convert to rgb color and as bg color
rgb.Println("message with rgb bgf color")
```

**Comment by rew1nter** [comment]
![image](https://github.com/gookit/color/assets/64508791/276e7b91-cf4d-4e0f-bb78-377a03a4bcca)
this is the color I'm talking about. It's definitely not #00FFFF

**Comment by inhere** [comment]
![image](https://github.com/gookit/color/assets/5302062/3f96b6a6-43d4-4af6-b123-1f525b7c2e8d)

HiCyan hex is `#68fdfe` 

https://github.com/gookit/color/blob/9027b9d2a5168ea482a8a8b46711191450514aa3/convert.go#L53-L91

**Comment by rew1nter** [comment]
Thanks.
