### ISSUE TITLE
Concurrency issues

### ISSUE THREAD

**Issue by SHT** [gookit/color#7]
On Windows, if there are many goroutines that try to write on the console (by using the Fprint function, for example), there is good chance the output will be scrambled, [like so](https://i.snipboard.io/Vmk1ew.jpg).

Removing the lines 184-187 on the file `color_windows.go` seems to fix this issue.

Not sure why the color setting needs to be reverted, is that needed?

**Comment by SHT** [comment]
Should be fixed with https://github.com/gookit/color/pull/12.

**Comment by inhere** [comment]
thanks you

**Comment by SHT** [comment]
Closing this for now, if need be it can be reopened.
