### ISSUE TITLE
hi powershell new version 7.x not work

### ISSUE THREAD

**Issue by godtoy** [gookit/color#9]
![image](https://user-images.githubusercontent.com/13638996/73273091-5cb46600-421e-11ea-8722-891f73533d1e.png)

PowerShell 7.0.0-rc.2

**Comment by inhere** [comment]
thanks you reports.

**Comment by inhere** [comment]
hi @godtoy 
It's works fine on PowerShell 7

see:

![color-demo](https://user-images.githubusercontent.com/5302062/78454953-0821e100-76ce-11ea-9eb6-352be6455ae4.PNG)

**Comment by inhere** [comment]
more tests:

![](https://github.com/gookit/color/blob/master/_examples/images/color-on-cmd-pwsh.jpg)
